### ISSUE TITLE
no difference between the sid debian version and 1.2 of release

### ISSUE THREAD

**Issue by alexmyczko** [isginf/libnfsidmap-regex#5]
Could you please elaborate what is the problem with the current version of libnfsidmap-regex in Debian sid, and the versions 1.1 and 1.2 released, apart of the version number?

```
$ debdiff libnfsidmap-regex_1.0+git20200429-1.dsc libnfsidmap-regex_1.2-1.dsc
dpkg-source: warning: extracting unsigned source package (/var/www/debian/libnfsidmap-regex/2020/libnfsidmap-regex_1.0+git20200429-1.dsc)
dpkg-source: warning: extracting unsigned source package (/var/www/debian/libnfsidmap-regex/2020/libnfsidmap-regex_1.2-1.dsc)
diff -Nru libnfsidmap-regex-1.0+git20200429/debian/changelog libnfsidmap-regex-1.2/debian/changelog
--- libnfsidmap-regex-1.0+git20200429/debian/changelog	2020-04-29 11:58:53.000000000 +0200
+++ libnfsidmap-regex-1.2/debian/changelog	2020-05-20 14:55:56.000000000 +0200
@@ -1,3 +1,9 @@
+libnfsidmap-regex (1.2-1) unstable; urgency=medium
+
+  * New upstream version.
+
+ -- Gürkan Myczko <gurkan@phys.ethz.ch>  Wed, 20 May 2020 14:55:56 +0200
+
 libnfsidmap-regex (1.0+git20200429-1) unstable; urgency=medium
 
   * New upstream version.
```

And I'm sorry I wasn't aware 1.1 was already pushed, so 1.2 is a nochange bump of the version (that wasn't needed either)

**Comment by isginf** [comment]
Not sure if there are problems. 1.1 was an intermediate release, just use 1.2.
Basically the new version should build on all distros, no matter what version of nfs-utils they use or upgrade to. The autoconf part has been improved to detect the small API changes the NFS devs did over time.
Apart of that the feature that brought in the dependency to an external INI parser has been removed.

**Comment by TheTyrius** [comment]
> the feature that brought in the dependency to an external INI parser has been removed.

Hello, since this has been removed, do you have a hint at how to best map between the "domain users" on the server and "users" on the client? I'd be grateful if you had any pointers to an alternative approach :)

Btw, the static mapping seems to be referenced in the README still, in case this feature is gone for good it could be removed I guess.
