### ISSUE TITLE
libnfsidmap-regex package broken in current LTS release (focal) / updating src:nfs-utils from 1.x to 2.x

### ISSUE THREAD

**Issue by alexmyczko** [isginf/libnfsidmap-regex#6]
a bug has been filed against ubuntu 20.04 LTS:
https://bugs.launchpad.net/ubuntu/+source/libnfsidmap-regex/+bug/1915130

the current debian sid version has a debian/README.Debian note saying:
This package is going to become obsolete soon.
Please look at nfs-utils-2-4-4-rc3+.

and debian sid has, `dpkg -l |grep nfs-utils`:
`ii  libnfs-utils                                         4.0.0-1                                              amd64        NFS client library (binaries)`

as the submitter already suggests, a rebuild probably fixes the problem...

what is the state on the need of this package?

@carnil this part for you?
however it doesn't look as good with
https://packages.debian.org/source/sid/nfs-utils

trying to get an update for it done, can you test when i do it?
http://sid.ethz.ch/debian/nfs-utils/

**Comment by carnil** [comment]
@alexmyczko late to respond to this issue, but here goes the answer for Debian's end: https://tracker.debian.org/news/1256348/accepted-nfs-utils-1254-1exp2-source-into-experimental/

In short: 2.5.4 noch reached finally Debian, but it is in experimental to first further expose for testing. That version takes over the libnfsidmap-regex package.

Edit: note nfs-utils and libnfs-utils are two different packages (the latter, is a binary package built from libnfs)
